#pragma once
#include <Windows.h>
#include <NuiApi.h>

using namespace std;
class JointData
{
	/*
	typedof enum _UI_SKELETON_POSITION_TRACKING_STATE
	{
		NUI_SKELETON_POSITION_NOT_TRACKED = 0,
		NUI_SKELETON_POSITION_TRACKED
	} NUI_SKELETON_POSITION_TRACKING_STATE;
	typedof enum _NUI_SKELETON_POSITION_INDEX
	{
		NUI_SKELETON_POSITION_HIP_CENTER = 0,
		NUI_SKELETON_POSITION_SPINE,
		NUI_SKELETON_POSITION_SHOULDER_CENTER,
		NUI_SKELETON_POSITION_HEAD,
		NUI_SKELETON_POSITION_SHOULDER_LEFT,
		NUI_SKELETON_POSITION_ELBOW_LEFT,
		NUI_SKELETON_POSITION_WRIST_LEFT,
		NUI_SKELETON_POSITION_HAND_LEFT,
		NUI_SKELETON_POSITION_SHOULDER_RIGHT,
		NUI_SKELETON_POSITION_ELBOW_RIGHT,
		NUI_SKELETON_POSITION_WRIST_RIGHT,
		NUI_SKELETON_POSITION_HAND_RIGHT,
		NUI_SKELETON_POSITION_HIP_LEFT,
		NUI_SKELETON_POSITION_KNEE_LEFT,
		NUI_SKELETON_POSITION_ANKLE_LEFT,
		NUI_SKELETON_POSITION_FOOT_LEFT,
		NUI_SKELETON_POSITION_HIP_RIGHT,
		NUI_SKELETON_POSITION_KNEE_RIGHT,
		NUI_SKELETON_POSITION_ANKLE_RIGHT,
		NUI_SKELETON_POSITION_FOOT_RIGHT,
		NUI_SKELETON_POSITION_FOOT_RIGHT,
		NUI_SKELETON_POSITION_COUNT
	} NUI_SKELETON_POSITION_INDEX;
	*/
public:
	LONG x, y, z;
	NUI_SKELETON_POSITION_TRACKING_STATE state;
	static const int segment[];
	static const int nseg;
public:
	JointData();
	~JointData();
};